version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5001:5432"
  api:
    depends_on:
      - postgres
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - PGPASSWORD=postgres
    ports:
      - "1000:3000"
